name: Github actions certified
on: push

jobs:
    build_job:
      runs-on: ubuntu-latest
      steps:
        - name: Install Cowsay
          run: sudo apt-get install cowsay -y

        - name: run Cowsay
          run: cowsay -f elephant "Incoming elephant.. RWRRR" >> elephant.txt
        
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.6.2
          with:
            name: elephant-txt-file
            path: elephant.txt
 
    test_job:
      needs: build_job
      runs-on: ubuntu-latest
      steps:
       
        - name: test file exists
          run: grep -i elephant elephant.txt 

    deploy_job:
      needs: [test_job]
      runs-on: ubuntu-latest
      steps:
        - name: read file
          run: cat elephant.txt
        
        - name: deploy
          run: echo "deploying.."
    
  
